name: Android CI

on:
  push:
    paths:
      - "AOS/**"
      - "**.yml"
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Access to secrets
        run: |
          echo SLACK_OAUTH_KEY=\"$SLACK_OAUTH_KEY" > ./AOS/local.properties
          shell: bash
          env:
            SLACK_OAUTH_KEY: ${{secrets.SLACK_OAUTH_KEY}}
            
      - name: Grant execute permission for gradlew
        run: chmod +x ./AOS/gradlew
      - name: Build with Gradle
        working-directory : ./AOS
        run: ./gradlew build
