name: Android CI

on:
  push:
    paths:
      - "AOS/**"
      - "**.yml"
    branches: [ "main", "**/ci-setting" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Make local.properties file
        env:
          SLACK_OAUTH_KEY: ${{secrets.SLACK_OAUTH_KEY}}
        run: echo "SLACK_OAUTH_KEY=\"$SLACK_OAUTH_KEY\"" > ./AOS/local.properties

      - name: Append gradle.properties file
        env:
          STORE_FILE_DEBUG: ${{ secrets.STORE_FILE_DEBUG }}
          STORE_PASSWORD_DEBUG: ${{ secrets.STORE_PASSWORD_DEBUG }}
          KEY_ALIAS_DEBUG: ${{ secrets.KEY_ALIAS_DEBUG }}
          KEY_PASSWORD_DEBUG: ${{ secrets.KEY_PASSWORD_DEBUG }}
          STORE_FILE: ${{ secrets.STORE_FILE }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run:
          echo "STORE_FILE_DEBUG=\"$STORE_FILE_DEBUG\"" > ./AOS/gradle.properties
          echo "STORE_PASSWORD_DEBUG=\"$STORE_PASSWORD_DEBUG\"" > ./AOS/gradle.properties
          echo "KEY_ALIAS_DEBUG=\"$KEY_ALIAS_DEBUG\"" > ./AOS/gradle.properties
          echo "KEY_PASSWORD_DEBUG=\"$KEY_PASSWORD_DEBUG\"" > ./AOS/gradle.properties
          echo "STORE_FILE=\"$STORE_FILE\"" > ./AOS/gradle.properties
          echo "STORE_PASSWORD=\"$STORE_PASSWORD\"" > ./AOS/gradle.properties
          echo "KEY_ALIAS=\"$KEY_ALIAS\"" > ./AOS/gradle.properties
          echo "KEY_PASSWORD=\"$KEY_PASSWORD\"" > ./AOS/gradle.properties

      - name: Create Keystore File
        env:
          DEBUG_KEYSTORE: ${{secrets.KEY_BASE_64_DEBUG}}
          RELEASE_KEYSTORE: ${{secrets.KEY_BASE_64_RELEASE}}
        run:
          echo "$DEBUG_KESTORE" > ./AOS/app/keystore/debug_keystore.b64
          base64 -d -i ./AOS/app/keystore/debug_keystore.b64 > ./AOS/app/keystore/debug.keystore
          echo "$RELEASE_KESTORE" > ./AOS/app/keystore/release_keystore.b64
          base64 -d -i ./AOS/app/keystore/release_keystore.b64 > ./AOS/app/keystore/release.keystore
      
      
      - name: Grant execute permission for gradlew
        run: chmod +x ./AOS/gradlew
      - name: Build with Gradle
        working-directory : ./AOS
        run: ./gradlew build
